### ISSUE TITLE
Unresolved requirements osgi.extender; (&(osgi.extender=osgi.cdi)(version>=1.0.0)(!(version>=2.0.0)))

### ISSUE THREAD

**Issue by mkovacek** [Sandared/osgi-openapi-example#1]
Hi,

First of all thanks for an example of how to integrate OpenAPI.

I was trying to integrate OpenAPI with Aries JAX-RS in Apache Felix following your example and documentation from Aries
https://github.com/apache/aries-jax-rs-whiteboard/tree/org.apache.aries.jax.rs-1.1.0/integrations

But it seems that I'm missed something. I'm not able to satisfy the 
`Require-Capability: osgi.extender; filter:="(&(osgi.extender=osgi.cdi)(version>=1.0.0)(!(version>=2.0.0)))"`

That is generated in manifest when I add 

`        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-jaxrs2</artifactId>
            <version>2.1.1</version>
         </dependency>
`

Did you have this issue or any idea how to solve it?

**Comment by Sandared** [comment]
This looks to me as if either your code or maybe the aries whiteboard uses
CDI annotations and therefore requires the cdi extender... Do you have your
code in a public repo?

If Not then I would recommend that you try to find out from where in your
code/dependencies this requirement comes from and remove it OR you could
Install the required CDI extender too in your runtime.

A general advise would be to use Apache Karaf instead of a bare Felix
runtime. I myself once started with Felix but then switched to karaf,
because it makes OSGi development so much easier ;)

Hope that helps :)

Kind regards,
Thomas


Matija Kovaček ***@***.***> schrieb am So., 14. März 2021,
09:10:

**Comment by mkovacek** [comment]
Thanks Thomas :)

Could be Aries whiteboard, since at the moment I don't have any of my code. Will recheck it there.

Unfortunately, I need to stick to Apache Felix cause I'm working with Adobe Experience Manager (AEM). 
 
Basically what I'm trying to achieve is to create some kind of wrapper project of Aries JAX-RS whiteboard with Jackson and open API integrations + all dependencies. 

So that every AEM project can use this project as a dependency to have a clean starting base to develop REST services. Idea is to avoid this dependency (transitive) hell in every AEM project.

https://github.com/mkovacek/aem-jaxrs/tree/feature/aries-jax-rs-whiteboard-setup/3rd-party-aries-jax-rs-open-api

This is still under development, but maybe you will catch something.

Regards,
Matija

**Comment by Sandared** [comment]
Hm ... Nothing obvious.

Maybe you could check the manifests of the dependencies jars If one of them
pulls in the requirement?

Matija Kovaček ***@***.***> schrieb am So., 14. März 2021,
10:09:
